name: Automatic build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt install squashfs-tools squashfuse librsvg2-bin binutils-aarch64-linux-gnu
        sudo snap install go --classic

    - name: Build
      run: ./build.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: false
        title: "Nightly Build"
        files: |
          *.AppImage
          *.shImg
          *.zsync
