name: Push build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt install squashfs-tools squashfuse librsvg2-bin binutils-aarch64-linux-gnu musl musl-tools
        sudo snap install go --classic

    - name: Build
      run: ./build.sh

    - name: Build in chroot (aarch64)
      run: |
        wget https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.squashfs
        sh build_in_chroot.sh arm64

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: false
        title: "Nightly Build"
        files: |
          *.AppImage
          *.shImg
          *.zsync
